#ifndef POKKETSTATION_DESKTOP_RESOURCE_H
#define POKKETSTATION_DESKTOP_RESOURCE_H

#define IDI_MAINICON 100

#define IDR_MAINMENU 201
#define IDD_HWID 202
#define IDD_CUSTOM_COLORS 203
#define IDD_SHADOW_COLOR 204
#define IDD_REMAP_CONTROLS 205
#define IDD_CAPTURE_PROMPT 206
#define IDD_ABOUT 207

#define IDC_HWID_EDIT 1001
#define IDC_PIXEL_HEX 1002
#define IDC_PIXEL_CHOOSE 1003
#define IDC_BG_HEX 1004
#define IDC_BG_CHOOSE 1005
#define IDC_SHADOW_HEX 1006
#define IDC_SHADOW_CHOOSE 1007
#define IDC_SHADOW_RESET 1008
#define IDC_CAPTURE_PROMPT_TEXT 1009
#define IDC_ABOUT_LINK 1025
#define IDC_ABOUT_VERSION 1026
/* 5 consecutive IDs each, one per button in fixed Up/Down/Left/Right/Fire
   order (see button_scancodes in main.c) - IDC_REMAP_LABEL_BASE+i shows
   binding i's current key name, IDC_REMAP_CHANGE_BASE+i is that row's
   "Change..." button. */
#define IDC_REMAP_LABEL_BASE 1010
#define IDC_REMAP_CHANGE_BASE 1020

#define ID_FILE_OPEN_BIOS 1101
#define ID_FILE_OPEN_APP 1102
#define ID_FILE_EXIT 1103
#define ID_TOOLS_EDIT_HWID 1104
#define ID_TOOLS_REMAP_CONTROLS 1115
#define ID_HELP_ABOUT 1105
#define ID_VIEW_NATIVE_SIZE 1106
#define ID_VIEW_DOUBLE_SIZE 1107
#define ID_COLORS_STANDARD 1108
#define ID_COLORS_REVERSED 1109
#define ID_COLORS_CLASSIC 1110
#define ID_COLORS_CUSTOM 1111
#define ID_VIEW_SHADOWS_ENABLE 1112
#define ID_VIEW_SHADOWS_DISABLE 1113
#define ID_VIEW_SHADOW_COLOR 1114

#endif
